Demo
rhythmictech/terraform-aws-rhythmic-monitoring pull request #2
Opened 2020-06-02 01:29 UTC by cdaniluk

Not really looking to make this perfect. In building this, I've realized that we absolutely _have_ to have some sort of layer in between the AWS events and the target to route appropriately. Everything is too coarse. There are so many influencers of whether an alert should wake you up, create a non-urgent alert, create a ticket, generate a slack notice or be discarded. But for now this shows TF's role in what we can do. I think we probably need to create a layer in between that talks to something like this, that speaks its language.

To be able to use this effectively, we'd need to make it support CloudWatch Alarms, Metric Filters (slightly different), CloudWatch Events and a couple of other things that aren't quite the same. AND figure out severity/routing on top of that.

2020-06-02 01:54 UTC, sblack4 requested changes
The build is failing because two files don't have newlines at the EOF. Other than that I looks 🔥 

pre-commit-hook output:
```
Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing outputs.tf
Fixing .gitignore
```

2020-06-02 01:54 UTC, sblack4 commented on .gitignore
> +.DS_Store
No newline at the EOF

2020-06-02 01:54 UTC, sblack4 commented on jira.tf
> +  filename         = "${path.module}/create_jira.zip"
We don't have a rule for this but if I reference an interpolated string more than once I like it to be a local

2020-06-02 01:54 UTC, sblack4 commented on outputs.tf
> +}
no newline at the EOF

2020-06-02 01:54 UTC, sblack4 commented on .gitignore
> +.DS_Store
```suggestion
.DS_Store

```

2020-06-02 01:54 UTC, sblack4 commented on outputs.tf
> +}
```suggestion
}

```

2020-06-02 13:15 UTC, dgoodellrhy commented
> The build is failing because two files don't have newlines at the EOF. Other than that I looks 🔥
> 
> pre-commit-hook output:
> 
> ```
> Fix End of Files.........................................................Failed
> - hook id: end-of-file-fixer
> - exit code: 1
> - files were modified by this hook
> 
> Fixing outputs.tf
> Fixing .gitignore
> ```

Is there a good technical reason to block on missing EOF?  Does it break something?

2020-06-02 13:30 UTC, sblack4 commented
> > The build is failing because two files don't have newlines at the EOF. Other than that I looks 🔥
> > pre-commit-hook output:
> > ```
> > Fix End of Files.........................................................Failed
> > - hook id: end-of-file-fixer
> > - exit code: 1
> > - files were modified by this hook
> > 
> > Fixing outputs.tf
> > Fixing .gitignore
> > ```
> 
> Is there a good technical reason to block on missing newlines at EOF? Does it break something?

Is pedantry a good reason? It does break the build, but the build only checks the pre-commit hooks which don't do anything of substance. I'd argue that it's easy to just commit the suggested newlines through the PR UI so why not.

2020-06-03 18:16 UTC, cdaniluk commented
> > > The build is failing because two files don't have newlines at the EOF. Other than that I looks 🔥
> > > pre-commit-hook output:
> > > ```
> > > Fix End of Files.........................................................Failed
> > > - hook id: end-of-file-fixer
> > > - exit code: 1
> > > - files were modified by this hook
> > > 
> > > Fixing outputs.tf
> > > Fixing .gitignore
> > > ```
> > 
> > 
> > Is there a good technical reason to block on missing newlines at EOF? Does it break something?
> 
> Is pedantry a good reason? It does break the build, but the build only checks the pre-commit hooks which don't do anything of substance. I'd argue that it's easy to just commit the suggested newlines through the PR UI so why not.

In my opinion, having a 0 lint policy means that we won't have module cleanups down the line, which keeps change sets to only what actually _changed_ in the module and not what was cleaned up from prior failed lint jobs.

So I'm okay hardlining on this particular type of pedantry.

2020-06-03 19:01 UTC, sblack4 approved these changes

2020-06-03 21:03 UTC, smiller171 commented
also @dgoodellrhy If you set up `pre-commit` on your local machine these errors will be automatically fixed locally before you ever push

2020-06-03 21:36 UTC, smiller171 commented
I've now updated the template repo so it'll automatically commit any changes from the linters

https://github.com/rhythmictech/terraform-anycloud-template/pull/8

2020-10-13 13:21 UTC, sblack4 approved these changes
Is it ready for a release and the registry?

2020-10-13 13:21 UTC, sblack4 commented on README.md
> +| terraform | >= 0.13.0 |
😾 I hope it's not hard to upgrade our everything

2020-10-14 13:46 UTC, merged